// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("Transactions", testTransactions)
}

func TestDelete(t *testing.T) {
	t.Run("Transactions", testTransactionsDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("Transactions", testTransactionsQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("Transactions", testTransactionsSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("Transactions", testTransactionsExists)
}

func TestFind(t *testing.T) {
	t.Run("Transactions", testTransactionsFind)
}

func TestBind(t *testing.T) {
	t.Run("Transactions", testTransactionsBind)
}

func TestOne(t *testing.T) {
	t.Run("Transactions", testTransactionsOne)
}

func TestAll(t *testing.T) {
	t.Run("Transactions", testTransactionsAll)
}

func TestCount(t *testing.T) {
	t.Run("Transactions", testTransactionsCount)
}

func TestHooks(t *testing.T) {
	t.Run("Transactions", testTransactionsHooks)
}

func TestInsert(t *testing.T) {
	t.Run("Transactions", testTransactionsInsert)
	t.Run("Transactions", testTransactionsInsertWhitelist)
}

func TestReload(t *testing.T) {
	t.Run("Transactions", testTransactionsReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("Transactions", testTransactionsReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("Transactions", testTransactionsSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("Transactions", testTransactionsUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("Transactions", testTransactionsSliceUpdateAll)
}
